version: '3.3'
services:
  # backend:
  #   build: ./backend
  #   tty: true
  #   volumes:
  #     - ./backend:/app
  frontend:
    build:  
      context: ./front
      dockerfile: Dockerfile.dev
    tty: true
    stdin_open: true
    env_file: 
      - .env
    environment:
      CHOKIDAR_USEPOLLING: "true"
      # - NODE_ENV=development
    volumes:
      - ./front:/var/app
      - /var/app/node_modules
    command: sh -c "npm start"
    ports:
      - "${REACT_FRONT_PORT}:3000"
    # depends_on:
    #   - backend