version: "3.8"
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app_front/node_modules
      - /app_front/.next
      - ./front:/app_front
    ports:
      - "3000:3000"
  # front:
  #   build:  
  #     context: ./front
  #     dockerfile: Dockerfile
  #   tty: true
  #   # stdin_open: true
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   volumes:
  #     - /code/node_modules
  #     - ./front:/code
  #   command: sh -c "cd /code && yarn start"
  #   ports:
  #     - "3000:3000"
  #   # depends_on:
  #   #   - backend